export const REQUEST_AUTH_TOKEN = 'REQUEST_AUTH_TOKEN'
export const AUTH_TOKEN_RECEIVED = 'AUTH_TOKEN_RECEIVED'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'

export const FETCH_JOBS = 'FETCH_JOBS'
export const RECEIVE_JOBS = 'RECEIVE_JOBS'
